### ISSUE TITLE
DataBase Users

### ISSUE THREAD

**Issue by NNikiforov** [Hramkanvas/Blue#12]

**Comment by NNikiforov** [comment]
Готова схема. Структура схемы:
{
username,
FIO,
balance,
history {
                   previous: Array,
                    current: Array,
                    next: Array
            }
}

**Comment by NNikiforov** [comment]
Готовы функции:
-  пополнения баланса пользователя. - upBalance
-  добавления даты заказа в историю - addOrderToHistory
- добавления Юзера в БД - addUser

**Comment by AlexZetto** [comment]
Мы добавляем юзера в базу тогда, когда он делает заказ впервые, правильно?

Если так, то необходим метод, который позволит узнать, нужно ли добавлять пользователя в базу данных (существует ли такой пользователь).

**Comment by AlexZetto** [comment]
А лучше, чтобы он был только внутри базы и при добавлении нового заказа в базу вызывал метод  addUser, если такого пользователя нет

**Comment by NNikiforov** [comment]
Сделаны все требующиеся функции:

- Добавить заказ(дата) addOrderToHistory(username, date)
- Удалить заказ(дата) deleteOrderFromHistory(username, date)
- Изменить баланс upBalance(username, amount)
- Вернуть заказы на некоторую неделю getOrders(username, date)
- Вернуть ФИО getFIO(username)
- Вернуть баланс getBalance(username)
