### ISSUE TITLE
Write web component  pie-table-orders

### ISSUE THREAD

**Issue by yaliza** [Hramkanvas/Blue#16]
component "pie-table-orders"  include searching input, choosing day of the week and table orders.

**Comment by sharitonchik** [comment]
Список того что нужно сделать в рамках одного ишью достаточно большой получился, можно разбить на более мелкие и создать отдельные ишьи

**Comment by Hramkanvas** [comment]
# **PAsha**, please, don't create that thing: "choosing day"
It's not necessary at all
