### ISSUE TITLE
clean code

### ISSUE THREAD

**Issue by yaliza** [Hramkanvas/Blue#8]
Найти рекомендации по выбору нотации для всего проекта.
РАССКАЗАТЬ ВСЕМ КАК НАДО ДЕЛАТЬ. ДОГОВОРИТЬСЯ СО ВСЕМИ.

Переделать все как договорились. 
Ветка - clean_code

**Comment by Hramkanvas** [comment]
JS naming: https://github.com/airbnb/javascript/tree/es5-deprecated/es5#naming-conventions
CSS naming: https://github.com/airbnb/javascript/tree/master/css-in-javascript#naming
